---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb-0
    app: mongodb-1
    app: mongodb-2
  type: LoadBalancer
  ports:
    - name: tcp-27017
      nodePort: 32001
      protocol: TCP
      port: 27017
      targetPort: 27017
    - name: tcp-27018
      nodePort: 32002
      protocol: TCP
      port: 27018
      targetPort: 27018
    - name: tcp-27019
      nodePort: 32003
      protocol: TCP
      port: 27019
      targetPort: 27019
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-0
  labels:
    env: test
    app: mongodb-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-0
  template:
    metadata:
      labels:
        app: mongodb-0
    spec:
      containers:
        - name: mongodb-0
          image: mtlbillyfong/mongodb-replica-set:20200330-stable-1
          ports:
            - containerPort: 27017
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: "admin"
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: "MyPassword"
            - name: "MONGODB_ID"
              value: "mongo-0"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-1
  labels:
    env: test
    app: mongodb-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-1
  template:
    metadata:
      labels:
        app: mongodb-1
    spec:
      containers:
        - name: mongodb-1
          image: mtlbillyfong/mongodb-replica-set:20200330-stable-1
          ports:
            - containerPort: 27018
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: "admin"
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: "MyPassword"
            - name: "MONGODB_ID"
              value: "mongo-1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-2
  labels:
    env: test
    app: mongodb-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-2
  template:
    metadata:
      labels:
        app: mongodb-2
    spec:
      containers:
        - name: mongodb-2
          image: mtlbillyfong/mongodb-replica-set:20200330-stable-1
          ports:
            - containerPort: 27019
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: "admin"
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: "MyPassword"
            - name: "MONGODB_ID"
              value: "mongo-2"