---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb-0
spec:
  selector:
    app: mongodb-0
  type: LoadBalancer
  ports:
    - name: tcp-27017
      nodePort: 32001
      protocol: TCP
      port: 27017
      targetPort: 27017
  externalIPs:
    - 87.15.22.12
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-0
  labels:
    env: test
    app: mongodb-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-0
  template:
    metadata:
      labels:
        app: mongodb-0
    spec:
      containers:
        - name: mongodb-0
          #image: mongo
          image: mtlbillyfong/mongodb-replica-set:20200330-stable-1
          ports:
            - containerPort: 27017
          env:
            - name: "MONGO_INITDB_ROOT_USERNAME"
              value: "admin"
            - name: "MONGO_INITDB_ROOT_PASSWORD"
              value: "MyPassword"
            - name: "MONGODB_ID"
              value: "mongo-0"